### ISSUE TITLE
Kontakt Footer hinzufügen

### ISSUE THREAD

**Issue by maknoll** [Makerburg/makerburg.github.io#11]
Kontaktdaten in einem Footer zum default Layout hinzufügen.

Dafür klären:
- Emailaddresse
- Telefonnummer

**Comment by theandrelf** [comment]
Emailadresse: domain makerburg.de klicken und sowas ala mail@makerburg.de einrichten. Dann nur noch festlegen an wen die mails gehen und wer drauf antwortet
