### ISSUE TITLE
Overralls

### ISSUE THREAD

**Issue by theandrelf** [Makerburg/makerburg.github.io#13]
Wir brauchen Overralls. 
Ich mag grau, oder dunkles Blau. Aber nicht dieses Arbeitsjacken-Blau, das nicht. Grün ist auch doof. Rot wäre ok. Braun nicht.

Den hier z.B.: http://www.ebay.de/itm/Overall-Blaumann-Arbeitskleidung-Hard-Core-Schwarz-Gr-M-XXL-NEU-EXKLUSIV/301536977513

**Comment by maknoll** [comment]
Bin ich ehrlich gesagt nicht so scharf drauf. Ich denke mal selbst wenn wir die hätten würde ich die zur Arbeit nicht anziehen.

Wie wärs denn erstmal mit Shirts?

**Comment by theandrelf** [comment]
Ok. Ich hätte gerne nen Overall und würde den zum Arbeiten auch anziehen. Dann klick ich mir mal selbst bei Gelegenheit einen.
T-Shirts können wir natürlich trotzdem machen, fänd ich auch cool. Extra issue dafür?

**Comment by maknoll** [comment]
Yo #15
