### ISSUE TITLE
riesigen Textblob entfernen

### ISSUE THREAD

**Issue by maknoll** [Makerburg/makerburg.github.io#14]
ich finde, der riesige Textblob auf der Startseite muss weg. Die meisten werden dass nicht lesen. Wir sollten das ersetzen durch eine mit Icons und kurzen Absätzen aufbereitete Vorstellung.

**Comment by theandrelf** [comment]
12 Zeilen find ich jetzt nicht wirklich lang. Aber gut, die Jugend heutzutage findet auch Twitter zu textlastig :)
Ich wollte halt bisl Inhalt auf die Seiten bringen. Nun gut, daran sollte es nicht scheitern.
Icons und kurze Absätze find ich aber auch gut. Ist vermutlich übersichtlicher.

**Comment by maknoll** [comment]
Ich habs ein bisschen aufgelockert, ohne Inhalt zu entfernen.

**Comment by theandrelf** [comment]
Sieht schick aus. I like.
