### ISSUE TITLE
Staubsauger

### ISSUE THREAD

**Issue by maknoll** [Makerburg/makerburg.github.io#4]

**Comment by Hichi** [comment]
Also ich habe mir jetzt eine ganze Menge Staubsauger auf Ebay und Amazon angeschaut, die von Metabo und Bosch konnte mich nicht so recht überzeugen. Wenn ihr keinen besseren Vorschalg habt, dann wird es der hier: http://www.amazon.de/Einhell-TE-VC-2230-Nass-Trockensauger-Edelstahlbeh%C3%A4lter/dp/B00BLZVL7E/ref=cm_cr_pr_product_top#Ask + Staubsaugerbeutel mit Fließ
http://www.amazon.de/Vlies-Staubsaugerbeutel-passend-Einhell-TE-VC/dp/B00ENM97IM/ref=pd_sim_diy_3?ie=UTF8&refRID=1HJKQYHPWREZWVG4TCWP

**Comment by maknoll** [comment]
Objektiv spricht nichts dagegen. Aus reinem Hang zur Marke find ich den http://www.amazon.de/Metabo-602012000-AS-20-Allessauger/dp/B00DVFMZ9A/ref=pd_sim_diy_5?ie=UTF8&refRID=06WH8VPGMRP9CP7V9HFM attraktiver, in 20L hat der mehr Leistung und ist billiger, in 32L ist der 20 € teurer bei gleichem Volumen. Edelstahlbehälter haben die aber beide nicht, der Einhell schon...

**Comment by Hichi** [comment]
Besort und schon benutzt.
